### ISSUE TITLE
No point estimates for intercept and slope

### ISSUE THREAD

**Issue by chenkaiwu** [IALSA/IALSA-2015-Portland#10]
No point estimates for intercept and slope in either univariate or bivariate models

**Comment by andkov** [comment]
closed, seems dead

**Comment by wibeasley** [comment]
Hi @chenkaiwu, it appears to us that this is no longer a problem/issue.

If we're wrong, and you feel this may still need attention, please "reopen" the issue (see the button near the bottom of the page), and provide some a little more explanation please.
