### ISSUE TITLE
Coping folder named "libs" over from ialsa-2015-portland

### ISSUE THREAD

**Issue by Maleeha** [IALSA/IALSA-2015-Portland#116]
libs had the following folders:
- [x] css
- [x] images
- [x] materials
- [x] README.md
- [x] test.png
- [x] Thumbs.db

Everything seems to be have copied over, just fine.

**Comment by wibeasley** [comment]
The thumbnails shouldn't make it into the repo.  I guess I need to adjust the .gitgnore file.

**Comment by wibeasley** [comment]
@maleeha, will you please move this issue over to the stencil repo instead?  If in doubt out issues on the stencil because it notifies fewer subscribers/users.

**Comment by Maleeha** [comment]
@wibeasley , i am sorry i thought i created it in stencil. I have both the repos open on screen.

**Comment by Maleeha** [comment]
@wibeasley, no thumbnails. Got it.
