### ISSUE TITLE
Inconsistent `physical_outcome` values

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#12]
@andkov & @ph-rast, there are inconsistent values for the physical outcome.  Notice some have
- [ ] unnecessary leading spaces
- [ ] inconsistent capitalization
- [ ] flat-out missspelleeings (eg, p**lu**monary)
- [ ] things that I may not know enough to catch (eg, maybe `normalwalk` and `walking`; maybe `PhysSymmary` is the same as something else)

I'm going to temporarily fixe *some* of these with `lower(str_trim())`.  But I suggest you address the underlying problems.

There are fewer problems with the cog outcomes.  I'm creating another issue for that (#13)

*(code in `./synthesis/model_synthesis.R`)*
```r
> sort(unique(ds$physical_outcome))
 [1] " pulmonary"    " pulmonaryfvc" "chairstand"    "flaminco"      "gripstrength" 
 [6] "muscle"        "nophys"        "noPhys"        "normalwalk"    "PhysSummary"  
[11] "plumonary"     "pulmonary"     "tug"           "walking" 
     
> table(ds$physical_outcome)
    pulmonary  pulmonaryfvc    chairstand      flaminco  gripstrength        muscle 
            8             7             2             2             2            10 
       nophys        noPhys    normalwalk   PhysSummary     plumonary     pulmonary 
            6            16             2             1             1            22 
          tug       walking 
            2            10 
```

**Comment by andkov** [comment]
This work led to script "./reports/rename_collapse/Track_renaming.R"
