### ISSUE TITLE
word tables

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#136]
The new report combines the two tables, for for some reason the formating does not transfer to the new table:

![image](https://cloud.githubusercontent.com/assets/2608073/16639232/77933a56-43a2-11e6-9566-e5e21a1ce813.png)

I wonder if the style can support two types of tables in the same document? @wibeasley

**Comment by wibeasley** [comment]
I'm surprised.  Are both tables using the "Compact" font style?

(You're not synced, so I can't check myself.)

**Comment by andkov** [comment]
I think i synced a few seconds later, after posting the comment. should be up now. https://github.com/IALSA/IALSA-2015-Portland/blob/master/sandbox/word-tables/seed-meta.Rmd

**Comment by wibeasley** [comment]
Closed.  On the phone we figured out that the blank cells weren't being assigned the "compact" style.  It was assigned the "normal" style, which had an extra space after each line.
