### ISSUE TITLE
merge conflicts

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#16]
@ph-rast & @andkov 

I wanted to make sure you knew about these merge conflicts.  They'll create a variety of problems downstream in the reports.  It looks like most (maybe all) of them were introduced in this commit: https://github.com/IALSA/IALSA-2015-Portland/commit/00069a6f2f9afbf7b2e84a1f4fd6f0ed4df08111

![image](https://cloud.githubusercontent.com/assets/1372890/6378939/2e0c0bfa-bcf4-11e4-8b42-bc1dcb2a83b3.png)

Also, is there supposed to be a `automation_result.csv` in the repository's root directory?
https://github.com/IALSA/IALSA-2015-Portland/blame/master/automation_result.csv#L122-L493

**Comment by wibeasley** [comment]
Also, fixing merge conflicts can be confusing.  Call me if you'd like some help.

**Comment by andkov** [comment]
yes, thank you, we noticed. we avoid this issue by reproducing the .csv each time we create reports. But I agree, some rule or mechanism should be developed to take prevent this

**Comment by wibeasley** [comment]
this appears resolved
