### ISSUE TITLE
The order of facets in parameter graphs

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#17]
The order of facets in the parameter graphs should be forced to the order of covariate set: (listed in the [README](https://github.com/IALSA/IALSA-2015-Portland/blob/master/studies/README.md) of the "./studies" folder 

0) empty : no covariate included into the model
1) age : age is entered as a baseline measure, second level
2) ae : age + education
3) aeh : age + education + height
4) aehplus: age + education + height + diabetes + smoking history + cardiovascular
5) full : all covariate availible in the study (will be different across studies)

**Comment by chenkaiwu** [comment]
Hi Andrey,

One quick question, is there a consistent naming convention we are using for specific cognitive and physical function (the _cognitiveSpecific part)? Thank you. Chenkai

**Comment by andkov** [comment]
Hi @chenkaiwu ,
   please use the Maelstrom naming as much as possible. You should have an email from Scott witha attached file named "Maelstrom Areas of Information _IALSA-2014-11-02_FINAL.DOCX". If you cannot match your variable to a name on that list, then create your own. Try to make it descriptive, yet succinct at the same time (hint: naming is hard)

**Comment by chenkaiwu** [comment]
Hi @andkov 

Sounds good. Naming is actually not difficult for my data. Just want to make sure naming is not causing any technical difficulties in pulling out information from the output files on your side. Thanks.

**Comment by andkov** [comment]
@chenkaiwu, good thinking, thanks for checking. As long as you keep the first 5 bits of the filename in the convention we started with - we are ok.

**Comment by andkov** [comment]
appears resolved
