### ISSUE TITLE
Correct domain groupings

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#170]
@ampiccinin ,

I have developed the extensions of forest plots to cover the `gait` and `grip` tracks. The only thing that is preventing me from producing plots is a small bin sizes of some of the cognitive domains (e.g. `verbal comprehension` has a single cognitive test).  This is related to the issue of grouping cognitive tests into larger clusters we call `domains`. 

Ideally, we would have a systematic methods of grouping cognitive measures into domains, which would be the same across all tracks (pulmonary, gait, grip). At the same time we might need to specify different domain mapping depending on the availability of measures and/or theoretical considerations of the paper in question.  I have developed the scripts to exercise both of these options. 

### Method A (general)
- please edit [`./reports/correlation-3/domain-grouping.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping.csv) if the consistent grouping of cognitive measures into domains is possible across all three tracks (and possibly cog-cog). Add the value in the `domain_new` column. 

### Method B (specific)
For each of the tracks, please edit:
- [`./reports/correlation-3/domain-grouping-gait.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping-gait.csv) 
- [`./reports/correlation-3/domain-grouping-grip.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping-grip.csv) 
- [`./reports/correlation-3/domain-grouping-pulmonary.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping-pulmonary.csv) 
to implement idiosyncratic domain grouping for each of the tracks.  Each of these files gives the current state of the data. Notice that [`./reports/correlation-3/domain-grouping-pulmonary.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping-pulmonary.csv)  is what you have provided ( 'NA` in `domain_new` columns indicates that the new domain has not been provided) earlier. 

If it is easier, I can use my own judgement for now, so forest plots can be produced and examined (and their grouping corrected). What breaks my scripts now is low bin size in some of the domains (e.g. `verbal comprehension` has a single cognitive test).  The rest of the architecture for correlation reports (including forest plots is ready).

**Comment by ampiccinin** [comment]
@andkov  - please use the simplified categorization I implemented in the correlations file I sent Sean:

[Correlation-3-women 2017-01-25.xlsx](https://github.com/IALSA/IALSA-2015-Portland/files/794260/Correlation-3-women.2017-01-25.xlsx)

**Comment by andkov** [comment]
@ampiccinin ,
  Great. That should be easy. I have applied the categorization you've mentioned to the pulmonary track. (FYI: the mapping you have provided has been reexpressed in  [`./reports/correlation-3/domain-grouping-pulmonary.csv`](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/correlation-3/domain-grouping-pulmonary.csv) so that they can be fed to the renaming script. )

If I understood you correctly, the plan is to apply the same categorization to the rest of the tracks. (Which makes sense because the cog measures _should_ be the same across tracks. Gee i'm a slow thinker today). 

When surveying the data for all the tracks, the following categorizations are missing from the scheme you have provided:
![image](https://cloud.githubusercontent.com/assets/2608073/23225471/03ac9d4e-f900-11e6-83be-e993933b6baf.png)

Would you agree with the following grouping decisions?

![image](https://cloud.githubusercontent.com/assets/2608073/23225369/a84acae8-f8ff-11e6-9392-ba428994b1f8.png)


P.S.  Congrats on the first file link! 👍

**Comment by ampiccinin** [comment]
@andkov - 

Yes - same categorization - at least for the three phys-cog (and very likely for cog-cog).

Yes - I agree with your grouping decisions.

:)
