### ISSUE TITLE
aehplus model warning in output

### ISSUE THREAD

**Issue by andreazammit** [IALSA/IALSA-2015-Portland#18]
I'm getting this warning when I run model 4. The model still terminates normally, so I'm unsure if I should change the starting values or leave it as is? I don't want to mess too much with the scripts that have been provided. Thanks a lot!

     WARNING: THE MODEL ESTIMATION HAS REACHED A SADDLE POINT OR A POINT WHERE THE
     OBSERVED AND THE EXPECTED INFORMATION MATRICES DO NOT MATCH.
     AN ADJUSTMENT TO THE ESTIMATION OF THE INFORMATION MATRIX HAS BEEN MADE.
     THE CONDITION NUMBER IS      -0.131D-06.
     THE PROBLEM MAY ALSO BE RESOLVED BY DECREASING THE VALUE OF THE
     MCONVERGENCE OR LOGCRITERION OPTIONS OR BY CHANGING THE STARTING VALUES
     OR BY USING THE MLF ESTIMATOR.

THE MODEL ESTIMATION TERMINATED NORMALLY

**Comment by GracielaMuniz** [comment]
One possible solution is to ? change the estimator to MLF, by adding the line :

ESTIMATOR=MLF

in the analysis command.

let us know if it helps, please.

best,

Graciela




?

Graciela Muniz-Terrera, PhD?
Programme Leader Track
MRC Unit for Lifelong Health and Ageing at UCL
33 Bedford Place
London WC1B 5JU?
UK.

phone: +44(0) 20 76705719
g.muniz@ucl.ac.uk

________________________________

**Comment by andreazammit** [comment]
Yes Graciela that seems to have worked - no warnings and the model terminated normally. 
Thanks a lot,
Andrea

**Comment by andreazammit** [comment]
Sorry me again - that issue was solved using univariate linear models, for univariate quadratic it give me this error - I tried several times using different starting values as well as the estimator=mlf but it still gives this statement. 

   THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO AN ILL-CONDITIONED
     FISHER INFORMATION MATRIX.  CHANGE YOUR MODEL AND/OR STARTING VALUES.

     THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A NON-POSITIVE
     DEFINITE FISHER INFORMATION MATRIX.  THIS MAY BE DUE TO THE STARTING VALUES
     BUT MAY ALSO BE AN INDICATION OF MODEL NONIDENTIFICATION.  THE CONDITION
     NUMBER IS       0.867D-11.

     THE STANDARD ERRORS OF THE MODEL PARAMETER ESTIMATES COULD NOT BE
     COMPUTED.  THIS IS OFTEN DUE TO THE STARTING VALUES BUT MAY ALSO BE
     AN INDICATION OF MODEL NONIDENTIFICATION.  CHANGE YOUR MODEL AND/OR
     STARTING VALUES.  PROBLEM INVOLVING THE FOLLOWING PARAMETER:
     Parameter 8, IC ON DIAB
 
For females.

Where as for males another parameter is the problem:
 Parameter 28, QC

Do you know what this might be?

Thanks so much,
Andrea

**Comment by GracielaMuniz** [comment]
?try adding s@0 in the model command. sometimes it could be that there is not enough variability across the individuals in their quadratic terms.

let us know if it works, pl.




?

Graciela Muniz-Terrera, PhD?
Programme Leader Track
MRC Unit for Lifelong Health and Ageing at UCL
33 Bedford Place
London WC1B 5JU?
UK.

phone: +44(0) 20 76705719
g.muniz@ucl.ac.uk

________________________________

**Comment by andreazammit** [comment]
Hi Graciela,
It didn't work. So I added i@0; s@0; (not sure we want to fix the variance at the intercept too? But it gave me new errors:

     THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A CHANGE IN THE
     LOGLIKELIHOOD DURING THE LAST E STEP.

     AN INSUFFICENT NUMBER OF E STEP ITERATIONS MAY HAVE BEEN USED.  INCREASE
     THE NUMBER OF MITERATIONS OR INCREASE THE MCONVERGENCE VALUE.  ESTIMATES
     CANNOT BE TRUSTED.
     SLOW CONVERGENCE DUE TO PARAMETER 16.
     THE LOGLIKELIHOOD DERIVATIVE FOR THIS PARAMETER IS  0.74213059D+03.



Andrea Zammit, PhD
Postdoctoral Research Fellow
Einstein Aging Study
1165 Morris Park Avenue
Rousso Building
Room 334
Bronx, New York 10461
Phone: (718) 430-3831
________________________________

**Comment by andreazammit** [comment]
Hi Graciela,
It didn't work. So I added i@0; s@0; (not sure we want to fix the variance at the intercept too? But it gave me new errors:

     THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A CHANGE IN THE
     LOGLIKELIHOOD DURING THE LAST E STEP.

     AN INSUFFICENT NUMBER OF E STEP ITERATIONS MAY HAVE BEEN USED.  INCREASE
     THE NUMBER OF MITERATIONS OR INCREASE THE MCONVERGENCE VALUE.  ESTIMATES
     CANNOT BE TRUSTED.
     SLOW CONVERGENCE DUE TO PARAMETER 16.
     THE LOGLIKELIHOOD DERIVATIVE FOR THIS PARAMETER IS  0.74213059D+03.

**Comment by GracielaMuniz** [comment]
try adding this in the analysis.


MITERATIONS=1000

If it does not work, try:
?
Mconvergence=0.001

?if neither works, try  both together & let me know how it works?

G





?

Graciela Muniz-Terrera, PhD?
Programme Leader Track
MRC Unit for Lifelong Health and Ageing at UCL
33 Bedford Place
London WC1B 5JU?
UK.

phone: +44(0) 20 76705719
g.muniz@ucl.ac.uk

________________________________

**Comment by ampiccinin** [comment]
If it's the quadratic model, should the change perhaps have been q@0, leaving I and s free?


On Feb 27, 2015, at 9:51 AM, andreazammit <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Graciela,
It didn't work. So I added i@0; s@0; (not sure we want to fix the variance at the intercept too? But it gave me new errors:

 THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A CHANGE IN THE
 LOGLIKELIHOOD DURING THE LAST E STEP.

 AN INSUFFICENT NUMBER OF E STEP ITERATIONS MAY HAVE BEEN USED.  INCREASE
 THE NUMBER OF MITERATIONS OR INCREASE THE MCONVERGENCE VALUE.  ESTIMATES
 CANNOT BE TRUSTED.
 SLOW CONVERGENCE DUE TO PARAMETER 16.
 THE LOGLIKELIHOOD DERIVATIVE FOR THIS PARAMETER IS  0.74213059D+03.


-

**Comment by GracielaMuniz** [comment]
Absolutely, that  is what I meant! Sorry if i wrote something else!!

Sent using OWA for iPhone
________________________________

**Comment by andreazammit** [comment]
I did try qc@0 and it still gave me the same errors. 
I ran them with MITERATIONS=1000; with Mconvergence=0.001; and with both together. And the best it gave me back is this: 

 THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A CHANGE IN THE
     LOGLIKELIHOOD DURING THE LAST E STEP.

     AN INSUFFICENT NUMBER OF E STEP ITERATIONS MAY HAVE BEEN USED.  INCREASE
     THE NUMBER OF MITERATIONS OR INCREASE THE MCONVERGENCE VALUE.  ESTIMATES
     CANNOT BE TRUSTED.
     SLOW CONVERGENCE DUE TO PARAMETER 16.
     THE LOGLIKELIHOOD DERIVATIVE FOR THIS PARAMETER IS  0.67031925D+03.

It seems to be a problem within the covariates. Depending on what I run e.g. if I run it normally I get an error of ic on diab; when I ran it with qc@0 I got ic on educ. However, I didn't get these porblems running the linear univariate or the bivariate models using these covariates. 

I tried increasing the number of iterations up to 3000 but it's still giving me this error.

**Comment by jru7sh** [comment]
Were you able to run the quadratic model without the additional covariates (i.e., only baseline age)?

**Comment by GracielaMuniz** [comment]
Isn't it tech 8 the tech request that lets you identify which is parameter16?

Sent using OWA for iPhone
________________________________

**Comment by andreazammit** [comment]
hi @jru7sh 
Yes, I was able to run up until model 3 (aeh). It's once I started adding additional covariates found in model4 (smoking, diabetes and CVD) that I started getting problems. 
I just tried running on a full model too (just GDS for depression) and it's still giving me the same problem. 
I tried fixing the variance at q@0 i@0 and s@0 as well as increasing the iterations, but it still gave me errors. 
Does it make sense to think the problem is in the covariates?

**Comment by andreazammit** [comment]
@GracielaMuniz 
I thought it was TECH1. I'll check now.

**Comment by jru7sh** [comment]
I think it is tech 1. @andreazammit if you add TECH1 to the output statement it will allow you to identify which parameter is creating the issue.

**Comment by GracielaMuniz** [comment]
Good, once that parameter is identified we can try to think of a solution- particularly as the more standard ones did not work.
I am in the middle of the meeting and without access to the manual, so trying to suggest solutions but not very accurately.sorry!

Sent using OWA for iPhone
________________________________

**Comment by andreazammit** [comment]
No worries Graciela I had to leave coz I have a appointment - I ran it before I left but it didnt make sense to me - I'll have a better look into it when I get back. I'll let you know.
Andrea

Sent from my iPhone

On Feb 27, 2015, at 4:05 PM, GracielaMuniz <notifications@github.com<mailto:notifications@github.com>> wrote:

Good, once that parameter is identified we can try to think of a solution- particularly as the more standard ones did not work.
I am in the middle of the meeting and without access to the manual, so trying to suggest solutions but not very accurately.sorry!

Sent using OWA for iPhone
________________________________

**Comment by GracielaMuniz** [comment]
Hi Andrea,
If you copied the main bits of the output ( where estimates are, not the Cis part),  we could look at it and attempt  to provide more  informed solutions ( no big promises though).
Best,
G

**Comment by andreazammit** [comment]
Hi @GracielaMuniz ,
Thanks a lot - I'm including here the descriptives - the cardio variable is the problem. I'm not sure why because it's all in binary. But I ran this model yesterday using a different cardio variable and the model terminated normally. Here is what the output looks like with the initial cardio variable.
Many thanks,
Andrea

     UNIVARIATE HIGHER-ORDER MOMENT DESCRIPTIVE STATISTICS

         Variable/         Mean/     Skewness/   Minimum/ % with                Percentiles
        Sample Size      Variance    Kurtosis    Maximum  Min/Max      20%/60%    40%/80%    Median

     C1                   23.720       0.572       9.000    0.67%      16.000     21.000     24.000
             150.000      69.695       0.762      57.000    0.67%      25.000     30.000
     C2                   23.865       0.519       9.000    0.68%      16.000     20.000     24.000
             148.000      77.657       0.027      52.000    0.68%      25.000     31.000
     C3                   24.321       0.441      10.000    1.83%      16.000     21.000     24.000
             109.000      69.723      -0.134      48.000    0.92%      26.000     30.000
     C4                   25.827       0.139      12.000    9.33%      20.000     24.000     25.000
              75.000      64.810      -0.495      44.000    1.33%      28.000     31.000
     C5                   26.483       0.460      12.000   12.07%      20.000     21.000     24.000
              58.000      94.353      -0.579      48.000    3.45%      28.000     35.000
     C6                   26.489      -0.021      12.000    6.38%      20.000     25.000     27.000
              47.000      55.058      -0.112      45.000    2.13%      29.000     33.000
     C7                   26.457       0.718      16.000    8.57%      20.000     24.000     24.000
              35.000      48.248      -0.006      44.000    2.86%      25.000     33.000
     C8                   26.172       0.013      12.000    6.90%      16.000     24.000     25.000
              29.000      65.453      -0.921      41.000    3.45%      28.000     32.000
     BAGE                  8.315       0.601       0.379    0.67%       3.306      6.027      7.492
             150.000      26.616      -0.119      25.962    0.67%       9.080     13.641
     HEIGHT               -2.673      -0.197     -24.000    0.67%      -9.000     -4.000     -3.000
             150.000      60.793      -0.142      15.000    0.67%      -1.000      4.000
     EDUC                  7.033      -0.142      -4.000    0.67%       5.000      5.000      7.000
             150.000      10.686      -0.031      13.000    6.67%       8.000     10.000
     DIAB                  0.200       1.500       0.000   80.00%       0.000      0.000      0.000
             150.000       0.160       0.250       1.000   20.00%       0.000      0.000
     SMOKHIST              0.553       6.414       0.000   50.00%       0.000      0.000      0.500
             150.000       0.727      61.305       9.000    0.67%       1.000      1.000
     CARDIO            10517.620      -0.907    9314.000    0.67%   10273.000  10459.000  10537.000
             150.000   75321.169       2.092   10907.000    0.67%   10605.000  10789.000

     THE MODEL ESTIMATION DID NOT TERMINATE NORMALLY DUE TO A CHANGE IN THE
     LOGLIKELIHOOD DURING THE LAST E STEP.

     AN INSUFFICENT NUMBER OF E STEP ITERATIONS MAY HAVE BEEN USED.  INCREASE
     THE NUMBER OF MITERATIONS OR INCREASE THE MCONVERGENCE VALUE.  ESTIMATES
     CANNOT BE TRUSTED.
     SLOW CONVERGENCE DUE TO PARAMETER 16.
     THE LOGLIKELIHOOD DERIVATIVE FOR THIS PARAMETER IS  0.67031925D+03.






MODEL RESULTS

                    Estimate

 IC         ON
    BAGE              -0.010
    EDUC               0.032
    HEIGHT            -0.003
    DIAB              -0.150
    SMOKHIST           0.052
    CARDIO             0.000

 SC         ON
    BAGE              -0.019
    EDUC               0.045
    HEIGHT            -0.007
    DIAB              -0.222
    SMOKHIST           0.069
    CARDIO             0.000

 QC         ON
    BAGE              -0.009
    EDUC               0.013
    HEIGHT             0.000
    DIAB              -0.113
    SMOKHIST           0.007
    CARDIO             0.000

 Intercepts
    C1                 0.000
    C2                 0.000
    C3                 0.000
    C4                 0.000
    C5                 0.000
    C6                 0.000
    C7                 0.000
    C8                 0.000
    IC                25.138
    SC                 4.502
    QC                 0.510

 Residual Variances
    C1                54.349
    C2                54.349
    C3                54.349
    C4                54.349
    C5                54.349
    C6                54.349
    C7                54.349
    C8                54.349
    IC                 0.000
    SC                 0.000
    QC                 0.027

**Comment by GracielaMuniz** [comment]
Are you sure you don’t have values other than 0/1 in that variable? It’s strange that the mean is so high. Maybe the missing values were coded differently.

**Comment by andreazammit** [comment]
Yes I'm sure. I checked: n is 2254 (380=1; 1874=0).
Could it be that I have too many missing values on some of the variables? And the problem manifests differently? Does that make sense in MPlus? 
I had to decrease my coverage in some instances (using pulmonary and TrailsB), and in some analyses the output tells me to increase my EM and H1 iterations due to convergance issues. This after I include in the analysis command miterations of up to 2000 and the MLF estimator. I have tried going down to 6 waves but maybe I should go down even more?

**Comment by andkov** [comment]
@andreazammit, this issue appears resolved to us. Please reopen the issue if continuation is necessary

**Comment by Conmon1993** [comment]
I am sorry to interrupt, but do you have any solutions? I have the same problem as andreazammit.

**Comment by ampiccinin** [comment]
Unfortunately we apparently did not document the solution here when the issue was closed.

My memory is that we used fewer waves of data (5?), eliminating those for which too few individuals had data.

Hope this helps.
