### ISSUE TITLE
Too few cases in the covariate categories

### ISSUE THREAD

**Issue by P-Handschuh** [IALSA/IALSA-2015-Portland#19]
Hello together,

I have a problem concerning too few cases in the covariates categories. For my third model cardiovascular disease is measured with heart attack and angina pectoris. In the case of women we only have two participants who had a heart attack. This is a problem for my bivariate models (not for the univariate). My solution is now Model 3 (univariate and bivariate) for all women without heart attack and just with Angina Pectoris but for men with both… or is there a problem with inconsistent use of covariates (but I have still the 2 female participants with heart attack included)?
A similar problem concerns a bivariate model of Handgrip and Spacial Ability for males for model2 and 3. As there is missing data there are - for this specific model - in one of my education category not enough cases (secondary school; I don’t have education in years). Now this is just one single case… can I create models without one of my three education categories or do I have to delete these 5 persons who were at a secondary school then (only for this model)?

Thank you for your help
Best 
Philipp

**Comment by andkov** [comment]
Hi @P-Handschuh, we are sorry this issue has been neglected. Please let us know if it still is relevant.
