### ISSUE TITLE
headings don't generate

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#20]
In [/scripts/x_individual_study_report.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/scripts/x_individual_study_report.R] lines 82-98
```
## @knitr freq_cog_specific

  for( cs in unique(dsb$cognitive_outcome)){
    ds <- dsb[dsb$cognitive_outcome==cs,]
    t7 <- table( ds$cognitive_specific, ds$study_name)
    t7[t7==0] <- "."

  cat(" ") #Force a new line
  cat(paste0("## ", cs))

  cat("\n") #Force a new line

    if( !is.na(t7[1])){
    print(ftable(t7))
    } else {
    cat("No specific for this outcome.*\n\n")
    }
    cat("\n")
}
```
do not produce the proper heading in the [markdown](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/minimalistic.html)

what might be the matter? Please take a look whenever you get a chance. hopefully something minor i'm missing.

**Comment by wibeasley** [comment]
Ran into this yesterday (and probalby 20 times before that).  Ensure that the `##` start on a new line.

```r
cat(paste0("\n\n## ", cs))
```

**Comment by andkov** [comment]
Thanks!

**Comment by andkov** [comment]
Nope. My joy was premature. The issue persists.  Will test further.

**Comment by wibeasley** [comment]
Make sure to look at the intermediate markdown for clues.  Also, trim down the complexity.  Start w/ something like this, and build up (assuming it works).

```r
## @knitr freq_cog_specific
for( cs in unique(dsb$cognitive_outcome)){

  cat(" ") #Force a new line
  cat(paste0("\n\n## Test Heading", cs))

  cat("\n") #Force a new line    
}
```

**Comment by andkov** [comment]
found it, @wibeasley 

In the Rmd file, the chunk must have the option **results="asis"**, not results="show". The latter forces the results to start and finish with ```, the code section markers.

**Comment by andkov** [comment]
Your intuition to look for clues in the .md was spot on.

**Comment by wibeasley** [comment]
I'm sorry, I knew that about  `results`, but didn't see and Rmd file in the script's neighborhood, and thought you were generating it differently.
