### ISSUE TITLE
Test for the number of componets

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#21]
I need to print the filenames that violate a particular naming convention.

The logic: if the filename doesn' t have exactly 7 components separated by undescores, then this file name should be printed.

the [script starter] (https://github.com/IALSA/IALSA-2015-Portland/blob/master/scripts/issues/test_for_number_of_components.R)

**Comment by wibeasley** [comment]
You were really close.  It needed just one more line of real code: `sapply(subparts, length)`.

The [overall code](https://github.com/IALSA/IALSA-2015-Portland/blob/master/scripts/issues/test_for_number_of_components.R) is
```r
desired_subpart_count <- 7L
ds$short <- gsub(".out","",ds$output_file)
subparts <- strsplit(ds$short,"_")
subpart_count <- sapply(subparts, length)
is_valid <- (subpart_count==desired_subpart_count)

ds$output_file[is_valid]
```

Does this help?  Thanks for putting the scaffolding together.

**Comment by andkov** [comment]
ah. thanks. i need to get  the apply family down my belt.
