### ISSUE TITLE
Print filenames on separate lines

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#22]
Please take a look when you got a sec.

When printing the names of the mislabeld models in [this report](https://htmlpreview.github.io/?https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/individual/eas.html#errors-of-omission) I would like each name to start on a separate line. 

Rmd: 129:130 ( "./reports/individual/eas.Rdm)
```
{r list.omissions, echo=echoChunks, message=FALSE}
```

R:89:97 ("./reports/individual/individualized.R)
```
desired_subpart_count <- 7L
ds$model_name <- gsub(pattern=".out",replacement="",ds$output_file) # remove .out ending
subparts <- strsplit(ds$model_name,"_") # break up each  model_name, store in a list
subpart_count <- sapply(subparts, length) # count compents in each element of the list
is_valid <- (subpart_count==desired_subpart_count) # create logical vector

if(sum(!is_valid)>0){ ds$output_file[!is_valid]}else{
  cat("All your models were named properly")
}
```

I've tried
```
 cat(ds$output_file[!is_valid],"\n")
```
but doesn't do the trick.

**Comment by wibeasley** [comment]
Check out the raw markdown for clues.  Remember you need need two new line characters most times in Markdown.  This may be overkill, but try

```
cat("\n\n", ds$output_file[!is_valid], "\n\n")
```

**Comment by andkov** [comment]
resolved. remember to set "results=" chunk option to "as is"
