### ISSUE TITLE
Merge 4 graphs into 1

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#23]
The report [OverlapVisualization](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/overlap_search_graphs/VisualizingOverlap.md) lists 4 graphs that exhaustively define a model with respect to its 1-2)measures, 3)study, 4)predictor sets, and 5)gender subgroup. These four graphs were manually combined as shown below
![overlap visual](https://raw.githubusercontent.com/IALSA/IALSA-2015-Portland/master/reports/overlap_search_graphs/figure_overlap/combine_panels-01.png)
We need to created something combining all four panels.

### Some guiding notes

1. The height of the tile graphs must be equal
2. The width of the tile must be equal across graphs

**Comment by andkov** [comment]
the basic solution could be found  in the Cookbook http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/

**Comment by andkov** [comment]
@wibeasley , please take a look. I've got it as far as I could tonight. The shiny app wouldn't build, give the same error

```
Listening on http://127.0.0.1:5489
ERROR: [on_request_read] connection reset by peer
Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
```

I'll be working through the bullet points on my own, but if you have a moment to look, it might go faster. I'm shooting for Monday afterenoon to show it in raw functionality.

the [commit](https://github.com/IALSA/IALSA-2015-Portland/commit/e30131b6f4c9f6a29aaac93aa7c24d655ca2ee15) sets up the basic compiled graph, stored at [shiny/dashboard/server.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/shiny/dashboard/server.R) script.


![issue25_tile_grid_graph](https://cloud.githubusercontent.com/assets/2608073/8028454/1faf56c4-0d63-11e5-8db2-1f789b5c4574.png)
)

Current goals:  
- [ ] customize <code>multiplot()</code> function in [server.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/shiny/dashboard/server.R) script, so that the relational size of each panel could have been passed as the function's argument.  
- [ ] adjust  <code>names_tile()</code> function to bring it into harmony with the other four tile plots  
- [ ] fine tune the  <code>basic_tile()</code>  function to make the tile plot area equal across all five (5) tiles plots

**Comment by wibeasley** [comment]
I don't see the problem.  Tomorrow I'll have time to pull the changes and run it myself.

Before you get too far with the composite graph, consider making them all in one ggplot.  Although I advocated for the `gridExtra`/`multiplot()` approach yesterday, but I'm changing my mind.  I think this can be all one ggplot, where it comes from all one dataset.  The intermediate dataset will need a new column that specifies physical_measure, study_name, predictor-set, or subgroup.    This character variable will map into the `fill` aesthetic.

Then a lot of cosmetic misalignments between subplots instantly go away, such as (a) distance from the bottom, (b) size of tiles, and (c) min/max intensity of legends.

**Comment by ialsa-lab** [comment]
I was just thing.  Make the x_name a variable and facet it by it. Fill as aestetic of a categorical variable, and then alpha as a continuous of the “n”. My only reservation is the sizes of the individual facet panel. Or… it would be irrelevant, because will adjust automatically?

In any case, I like one graph approach too. I’ll create a new script with that approach taken.

**Comment by wibeasley** [comment]
Hello robotic @ialsa-lab, 
I wasn't thinking of faceting, but I'm not opposed to it.  Now thtat I think about it, labeling the four sections would be easier.

If you faceted, I bet the `"free_x"` value for the scales parameter would do what you want.

http://docs.ggplot2.org/0.9.3.1/facet_grid.html
