### ISSUE TITLE
Missing data on covariates

### ISSUE THREAD

**Issue by casslbrown** [IALSA/IALSA-2015-Portland#25]
I have some cases with missing data on covariates with more missing on the plus model covariates. I was thinking of just bringing all the covariates into the model to be estimated but wanted to check with everyone. Do any of the other studies have this issue? Was it handled that way or were those cases taken out for all the models?

Thanks!

Cassandra

**Comment by andkov** [comment]
@casslbrown, have you received any consult on this issue outside of github? is it still relevant? please let me know so we either resolve or close this issue.

**Comment by casslbrown** [comment]
I have. I have brought the covariates into the model. It can be closed as an issue.
