### ISSUE TITLE
Tables of Studies & Contacts

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#26]
@andkov, I just converted the *list* of studies and contacts into a *table* in [README.md](https://github.com/IALSA/IALSA-2015-Portland/blob/master/README.md).  Delete whatever one you like least.

**Comment by andkov** [comment]
@wibeasley closed https://github.com/IALSA/IALSA-2015-Portland/commit/0fdab2fcb7687909ee747a3ebefd4b3d4e9125aa
