### ISSUE TITLE
Size of sidebarPanel

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#29]
The side bar panel in http://shiny.ouhsc.edu/IALSA-2015-Portland/shiny/bivariate_ISR/ is too wide. 

I would like to change the width of the sidebarPanel element.

typing ```sidebarPanel()``` into the panel produces
```
> sidebarPanel()
<div class="col-sm-4">
  <form class="well"></form>
</div> 
```
and i'm trying to control it with a [custom css](https://github.com/IALSA/IALSA-2015-Portland/tree/master/shiny/bivariate_ISR/www/custom.css)  
```
.col-sm-4{
  width: 200px;
}
```

after having attached it using them option in UI.R
```
shinyUI(fluidPage( theme = "custom.css",
```

but i don't think i'm getting it right. Any ideas, @wibeasley?

**Comment by wibeasley** [comment]
Before you spend time on this page layout, let's discuss if a [dashboard](http://rstudio.github.io/shinydashboard/) is a better fit for the present needs.

I've been very pleased how well the same app displays on big monitors as well as phones/tablets.

**Comment by andkov** [comment]
I like the dashboard idea and will play with it. I"m switching projects for a week ( from Portland to class prep ) but, coincidentally, it seems that i'll be needing dashboard for those ends too, so i'll be happy to play with it during the the next week as I'm prepping the lecture.
