### ISSUE TITLE
Appearance of Font

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#30]
Optimize the appearance of fonts in [./shiny/bivariate_ISR/](http://shiny.ouhsc.edu/IALSA-2015-Portland/shiny/bivariate_ISR/]

I've been having a hard time getting the fonts just right for the dynamic experience. Could you, @wibeasley please take a look at [./scripts/ISR_graph_functions.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/shiny/bivariate_ISR/scripts/ISR_graph_functions.R) to see how handling fonts can be optimized?

**Comment by wibeasley** [comment]
The HTML text, or text in the graphs?  When we talk about dashboards and #29, this may work itself out.

**Comment by andkov** [comment]
closed because we'll create dashboard instead. i'll reopen if it pertains in dashboards
