### ISSUE TITLE
Renaming and Classification system

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#34]
Create a dynamic system for correcting, renaming, and reclassifying values of a categorical variable, in this case of the variables that declare the constitution of the submitted models: model number, subgroup, physical outcome, physical outcome, cognitive outcome, physical specific, cognitive specific.

**Comment by wibeasley** [comment]
For when we talk about this next, here's an example of a csv that recodes 19 different entries (ie, the first column) into 5 categories (ie the last column).  Once a csv/table like this is created, the code is a very simple left join.

|Finding Type                                           | Finding Type ID| Approximate Count|Category Gut 5 |
|:-----------------------------------------------------|-----------------:|----------------:|:------------:|
|Unsubstantiated                                       |             19265|            54510|Good         |
|Ruled Out                                             |              1261|            44579|Good         |
|Services Recommended                                  |              5298|            42970|Bad          |
|Services Not Needed                                   |              5299|            39523|Good         |
|Substantiated                                         |             19264|            21355|Bad          |
|Unsubstantiated-Services Recommended                  |             18017|            19932|Good         |
|Confirm-Court Intervention Requested                  |              5296|            13680|Bad          |
|Substantiated-Court Intervention Recommended          |             18015|            12349|Bad          |
|Confirm-Services Recommended                          |              5297|            11515|Bad          |
|No Finding - Unable to Locate                         |              4098|             9789|Evaded       |
|No Finding - Failure to Cooperate                     |              6114|             8950|Evaded       |
|Substantiated-Services Recommended                    |             18016|             6690|Bad          |
|Uncertain                                             |              1262|             5345|Unknown      |
|Confirm                                               |              1259|             4814|Bad          |
|No Finding - Unable/Locate - Insufficient Family Info |             13996|              974|Evaded       |
|Improper Entry                                        |              5099|              688|Error        |
|Reasonable Parental Discipline                        |              4922|                3|Good         |
|NA                                                    |                 0|                3|Error        |
|Death-Pending M.E. Report                             |             19267|                1|Unknown      |

**Comment by wibeasley** [comment]
Here's a concrete example for IALSA, in case you're trying to explain it to someone else.  This csv/table is able to map the eight different responses in the left column (ie, those found in the datasets into two common categories in the right column.  If more responses arise in the future, you only have to add a few rows to the csv; the code is untouched.

| raw | polished |
|:--------------------------|:------------|
| grip | grip |
| GriP | grip |
| grip_strength | grip |
| hand_strength | grip |
| digit_span | digit_span |
| digit | digit_span |
| digitspan | digit_span |
| number_span | digit_span |

**Comment by wibeasley** [comment]
example code that's halfway between my example and yours

```r
dsFindingCategoryPhysical <- dsFindingCategory %>%
  dplyr::select(
    FindingPhysicalTypeID   = FindingTypeID,
    FindingPhysicalCategory = CategoryCut4
  ) %>%
  dplyr::filter(
    domain=="physical"
  )
  
dsFindingCategoryCognitive <- dsFindingCategory %>%
  dplyr::select(
    FindingCognitiveTypeID   = FindingTypeID,
    FindingCognitiveCategory = CategoryCut4
  ) %>%
  dplyr::filter(
    domain=="cognitive"
  )
  
dsAllegationLong <- dsAllegationLong %>%
  dplyr::left_join(dsFindingCategoryPhysical, by="FindingPhysicalTypeID")
  
dsAllegationLong <- dsAllegationLong %>%
  dplyr::left_join(dsFindingCategoryCognitive, by="FindingCognitiveTypeID")
```
