### ISSUE TITLE
NAS files breaks model extraction

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#42]
@wibeasley could you please investigate if you have a minute? I can't do it fast enough. When run for NAS the last big loop in [0a_functions_that_collect.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/scripts/0a_functions_that_collect.R) breaks.

**Comment by andkov** [comment]
@lewina mentioned:

In this last batch of file I uploaded, it included many more models. I added a cognitive outcome. I also used a different input dataset (because I had to recode some variables differently per discussion with Andrea). I re-ran everything from scratch, so unfortunately I can’t tell whether everything in the MODEL section remained the same for the models that were previously there.

**Comment by wibeasley** [comment]
The trouble starts in model 243 at 
```r
results[i, c("cov_int", "p_cov_int")] <-  IpH[grep("^I", IpH$param),c('est', 'pval')]
```

This regex is expecting to find a column that starts with an "I" in `IpH$param`.  But the one-element vector contains only `grep("^I", IpH$param)`.  So it returns a zero-length vector (when selecting rows from the `IpH` data.frame).  So that's why it throws the error message:
```
Error in `[<-.data.frame`(`*tmp*`, i, c("cov_int", "p_cov_int"), value = list( : 
  replacement has length zero
```

I'm not really sure of the code's intent, so I'm just making a guess.  Is there any chance the `paramHeader` and `param` columns were switched?  Because the former does have a cell that starts with `I`.
```r
> IpH
    paramHeader    param  est    se est_se pval
46 INCOME1.WITH MARRIED1 0.22 0.063  3.485    0
```

**Comment by andkov** [comment]
The code works for all other studies, and NAS previous submission. My guess is it's the output files, and in particular how the model components were named. Thanks, I'll use this as a starting point. I was surprise to see 243, I thought that was the total. The trouble started for me on 131.

**Comment by wibeasley** [comment]
I'd be interested if that was different for us.  See what the last output of this line is before the error.
```r
message("Getting ", study, ", model ", i, ".")
```

**Comment by andkov** [comment]
```
Getting nas, model 129.
Read 912 items
Error in `[<-.data.frame`(`*tmp*`, i, c("se_cov_slope"), value = c(0.006,  : 
  replacement has 8 rows, data has 1
In addition: Warning messages:
1: In `[<-.data.frame`(`*tmp*`, i, c("cov_slope", "p_cov_slope"), value = list( :
  replacement element 1 has 8 rows to replace 1 rows
2: In `[<-.data.frame`(`*tmp*`, i, c("cov_slope", "p_cov_slope"), value = list( :
  replacement element 2 has 8 rows to replace 1 rows
Called from: `[<-.data.frame`(`*tmp*`, i, c("se_cov_slope"), value = c(0.006, 
0.266, 0.138, 1.209, 1.021, 0.545, 4.474, 2.391))
```

**Comment by wibeasley** [comment]
I must have run past that one.  I see it now too.  Here's the vector the regex is trying to match against.  Does these suggest anything to you?
```r
> SpH$param
 [1] "IP"       "IP"       "SP"       "IC"       "MARRIED1" "INCOME1"  "DDEN_SR1" "DIS_BASE" "BLOCKS_F" "MARRIED1" "INCOME1"  "DDEN_SR1" "DIS_BASE" "BLOCKS_F"
[15] "STAIRS_F"
```
Is the regex too general?  It picks up any value that has an 'S' anywhere in the word.  Not necessarily at the beginning.
```r
grep("S", SpH$param)
```

**Comment by andkov** [comment]
```
"MARRIED1" "INCOME1"  "DDEN_SR1" "DIS_BASE" "BLOCKS_F" "MARRIED1" "INCOME1"  "DDEN_SR1" "DIS_BASE" "BLOCKS_F" "STAIRS_F"
```
is what new it seems to throw it off. Those are new in these models, so i'm not sure at this point whether to solve it through script of ask to re-run the models.

**Comment by wibeasley** [comment]
Are these different variables (not simply variables that were named differently)?  If so, do the model results have any purpose?

**Comment by andkov** [comment]
i"m not sure. @lewina, can you offer a comment? I think these are just variables named differently. To think about it, new variables shouldn't throw it off. The models would differ on the covariate (full type has unique sets of covariates across studies)

**Comment by lewina** [comment]
Hi,

 

Those are the covariates in the “full” model. These are newly added models (I didn’t have the “full” model in the last batch of files.)

 

Lewina

**Comment by andkov** [comment]
@wibeasley, this issue should be merged with #43 , is that a good practice from documentation perspective?

**Comment by wibeasley** [comment]
It's your preference.  In this situation, I think it's fine to explain the solution in one of the issues, and then link to it from the other issue.

**Comment by wibeasley** [comment]
@andkov has this issue been resolved?

**Comment by andkov** [comment]
It's been too long ago. I don't think it's relevant anymore. We are not using this study actively. Thanks for a reminder, I'm due for the next revision of issues and will rule on this issue in the few days
