### ISSUE TITLE
RADC : debugging extraction

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#43]
New model output files break code. (see #42 for NAS case).

Working with get.Models("radc") defined in [0a_functions_that_collect.R](https://github.com/IALSA/IALSA-2015-Portland/blob/master/scripts/0a_functions_that_collect.R)  

The script breaks with model 190

**Comment by andkov** [comment]
@wibeasley , I've been able to track the issue to the incorrect selection logic.

when extracting covariances the if statement we look for elements in paramHeader that has .WITH component. If there are more than 4 or these .WITH components we conclude that the model must be a bivariate, therefore covariances between intercepts, slopes, and residuals make sense and exist.
```
      ################# Covariances #################
      ## Look for at least 4 WITH statements
      ## otherwise fall back to 'Means' and 'Variances' (Baseline Models)
      ## this test seems wrong. The will be as many "WITH" as there are timepoints.
      modtype <- (length(grep("WITH", model$paramHeader))>=4)
      modtype
      if(modtype)
```

However, this logic breaks down when univariate models begin to include more than two predictors ( eah, eahplus, full). Compare the two models:
```
> i <- 189
> out_file <-  tail(strsplit(out_list[i],"/")[[1]], n=1)
> message("Getting ", study, ", model ", i, ", ",out_file)
Getting radc, model 189, u1_female_ae_nophys_speed_nophysspec_numbercomparison.out
> mplus_output <- scan(out_list[i], what='character', sep='\n')
Read 521 items
> model <- mpar[[i]]
> model
          paramHeader param    est    se  est_se    pval
1               IC.ON  BAGE -0.187 0.030  -6.352   0.000
2               IC.ON  EDUC  0.614 0.077   7.992   0.000
3               SC.ON  BAGE -0.031 0.007  -4.331   0.000
4               SC.ON  EDUC -0.019 0.018  -1.046   0.296
5             SC.WITH    IC  0.059 0.433   0.137   0.891
6           BAGE.WITH  EDUC -1.096 0.783  -1.401   0.161
7               Means  EDUC  7.337 0.098  75.070   0.000
8               Means  BAGE  8.665 0.250  34.639   0.000
9          Intercepts    C1  0.000 0.000 999.000 999.000
10         Intercepts    C2  0.000 0.000 999.000 999.000
11         Intercepts    C3  0.000 0.000 999.000 999.000
12         Intercepts    C4  0.000 0.000 999.000 999.000
13         Intercepts    C5  0.000 0.000 999.000 999.000
14         Intercepts    IC 21.902 0.681  32.175   0.000
15         Intercepts    SC  0.301 0.149   2.023   0.043
16          Variances  EDUC  9.633 0.552  17.439   0.000
17          Variances  BAGE 63.201 2.822  22.392   0.000
18 Residual.Variances    C1 14.987 0.799  18.758   0.000
19 Residual.Variances    C2 14.987 0.799  18.758   0.000
20 Residual.Variances    C3 14.987 0.799  18.758   0.000
21 Residual.Variances    C4 14.987 0.799  18.758   0.000
22 Residual.Variances    C5 14.987 0.799  18.758   0.000
23 Residual.Variances    IC 35.201 2.234  15.758   0.000
24 Residual.Variances    SC  0.371 0.151   2.463   0.014
> i <- 190
> out_file <-  tail(strsplit(out_list[i],"/")[[1]], n=1)
>     message("Getting ", study, ", model ", i, ", ",out_file)
Getting radc, model 190, u1_female_aeh_nophys_executive_nophysspec_digitordering.out
>     mplus_output <- scan(out_list[i], what='character', sep='\n')
Read 539 items
>     model <- mpar[[i]]
> model
          paramHeader  param    est    se  est_se    pval
1               IC.ON   BAGE -0.003 0.006  -0.500   0.617
2               IC.ON   EDUC  0.120 0.017   7.241   0.000
3               IC.ON HEIGHT  1.633 0.585   2.792   0.005
4               SC.ON   BAGE -0.003 0.002  -1.504   0.133
5               SC.ON   EDUC -0.007 0.005  -1.295   0.195
6               SC.ON HEIGHT  0.221 0.214   1.031   0.303
7             SC.WITH     IC -0.073 0.032  -2.282   0.022
8           BAGE.WITH   EDUC -1.096 0.783  -1.401   0.161
9         HEIGHT.WITH   EDUC  0.037 0.008   4.813   0.000
10        HEIGHT.WITH   BAGE -0.113 0.020  -5.683   0.000
11              Means   EDUC  7.337 0.098  75.069   0.000
12              Means   BAGE  8.665 0.250  34.638   0.000
13              Means HEIGHT -0.001 0.002  -0.355   0.722
14         Intercepts     C1  0.000 0.000 999.000 999.000
15         Intercepts     C2  0.000 0.000 999.000 999.000
16         Intercepts     C3  0.000 0.000 999.000 999.000
17         Intercepts     C4  0.000 0.000 999.000 999.000
18         Intercepts     C5  0.000 0.000 999.000 999.000
19         Intercepts     IC  6.419 0.141  45.571   0.000
20         Intercepts     SC  0.060 0.044   1.356   0.175
21          Variances   EDUC  9.633 0.552  17.438   0.000
22          Variances   BAGE 63.201 2.822  22.392   0.000
23          Variances HEIGHT  0.006 0.000  12.343   0.000
24 Residual.Variances     C1  1.313 0.065  20.223   0.000
25 Residual.Variances     C2  1.313 0.065  20.223   0.000
26 Residual.Variances     C3  1.313 0.065  20.223   0.000
27 Residual.Variances     C4  1.313 0.065  20.223   0.000
28 Residual.Variances     C5  1.313 0.065  20.223   0.000
29 Residual.Variances     IC  1.062 0.109   9.778   0.000
30 Residual.Variances     SC  0.023 0.013   1.745   0.081
```

we need a new, more flexible extraction rule

**Comment by wibeasley** [comment]
I would have preferred to inspect the model statement to determine if it's bivariate or univariate.  Let's talk about how to do that.  You have a much better feel for the range of model statements within the repo.  Are you free tonight?

**Comment by andkov** [comment]
yes, I can do anytime except ~ from 21:00 CDT to  ~ 22:30 CDT

**Comment by andkov** [comment]
I've compared equivalent models from EAS and RADC. There is an ambiguity regarding model specification, in particular about the covariance structure of fixed effects: in EAS specification the predictors are orthogonal, while in RADC they are allowed to correlated. @GracielaMuniz , @ph-rast , @smhofer , @ampiccinin  which of these is the right one?

**Comment by ampiccinin** [comment]
Seems to me that predictors are correlated by default.

If RAdC explicitly modelled covariant de among predictors, perhaps it was to deal with missing data (I.e. FIML)?

On Jul 10, 2015, at 5:07 PM, Andrey Koval <notifications@github.com<mailto:notifications@github.com>> wrote:


I've compared equivalent models from EAS and RADC. There is an ambiguity regarding model specification, in particular about the covariance structure of fixed effects: in EAS specification the predictors are orthogonal, while in RADC they are allowed to correlated. @GracielaMuniz<https://github.com/GracielaMuniz> , @ph-rast<https://github.com/ph-rast> , @smhofer<https://github.com/smhofer> , @ampiccinin<https://github.com/ampiccinin> which of these is the right one?

**Comment by casslbrown** [comment]
For RADC I did explicitly model all covariates to deal with missing data using FIML.


________________________________

**Comment by andkov** [comment]
@ampiccinin , @casslbrown , If predictors are correlated by default then where are the correlation among predictors on the output for EAS model shown above? I've checked  univariate models of all studies: all except RADC specifies model as

```
MODEL:
        ic sc | c1 - c8 AT time1-time8;
        ic sc ON Bage educ height;
        c1-c8 (res_c);
```
and not as 
```
MODEL:
          Bage;
          Educ;
          Height;
          ic sc | c1-c5 AT time1-time5;
          ic sc ON Bage Educ Height;
          c1-c5 (res_c);
```
and DO NOT include sections
```
BAGE     WITH
    EDUC              -1.096      0.783     -1.401      0.161

 HEIGHT   WITH
    EDUC               0.037      0.008      4.813      0.000
    BAGE              -0.113      0.020     -5.683      0.000
```
in the output.

I'm fine with either specification (correlation vs uncorrelated fixed effects), but in the present state, it appears to me that the models of RADC are not equivalent with those in other studies, because all other studies model predictors as uncorrelated.

**Comment by ampiccinin** [comment]
Not in the output. Just like not in any regression output.

On Jul 10, 2015, at 6:40 PM, Andrey Koval <notifications@github.com<mailto:notifications@github.com>> wrote:


@ampiccinin<https://github.com/ampiccinin> , @casslbrown<https://github.com/casslbrown> , If predictors are correlated by default then where are the correlation among predictors on the output for EAS model shown above? I've checked univariate models of all studies: all except RADC specifies model as

MODEL:
        ic sc | c1 - c8 AT time1-time8;
        ic sc ON Bage educ height;
        c1-c8 (res_c);


and not as

MODEL:
          Bage;
          Educ;
          Height;
          ic sc | c1-c5 AT time1-time5;
          ic sc ON Bage Educ Height;
          c1-c5 (res_c);


and DO NOT include sections

BAGE     WITH
    EDUC              -1.096      0.783     -1.401      0.161

 HEIGHT   WITH
    EDUC               0.037      0.008      4.813      0.000
    BAGE              -0.113      0.020     -5.683      0.000


in the output.

I'm fine with either specification (correlation vs uncorrelated fixed effects), but in the present state, it appears to me that the models of RADC are not equivalent with those in other studies, because all other studies model predictors as uncorrelated.

-

**Comment by andkov** [comment]
The following studies did not explicitly request to output  the covariances among fixed effects in univariate models: EAS, ELSA, HABC, ILSE, NuAge, OCTO, SATSA. There model specification looked like this:
```
MODEL:
        ic sc | c1 - c8 AT time1-time8;
        ic sc ON Bage educ height;
        c1-c8 (res_c);
```
(aside: @ampiccinin, please confirm whether I understood you correctly that model specification above allows fixed effects to covary, it just does not print it in the output unless requested specifically?)

Studies NAS (#42)  and RADC, however, specified the model like this:
```
MODEL:
          Bage;
          Educ;
          Height;
          ic sc | c1-c5 AT time1-time5;
          ic sc ON Bage Educ Height;
          c1-c5 (res_c);
```
producing an additional section in the output
```
BAGE     WITH
    EDUC              -1.096      0.783     -1.401      0.161

 HEIGHT   WITH
    EDUC               0.037      0.008      4.813      0.000
    BAGE              -0.113      0.020     -5.683      0.000
```
This output, @wibeasley, breaks our extraction script, because it's logical arguments  count the number of .WITH elements.

It appears that scripts should be developed that could work with both type of outputs and rely on something less variant for extraction.

**Comment by ampiccinin** [comment]
Hi Andrey – assuming this is what you mean? Good question about estimated vs printed in output. I believe the answer is yes, and in addition that when variances are requested, as in RADC and NAS, FIML kicks in so the results would no longer be based on complete cases (with respect to the covariates).


[cid:image002.png@01D0BCB6.2232D1D0][cid:image006.jpg@01D0BCB6.2232D1D0]

**Comment by ialsa-lab** [comment]
Ok, I need to keep this distinction in mind. Thanks!
