### ISSUE TITLE
Validate RADC

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#56]
Inspect the results extracted from the model output files provided by the study to the Collective.

The key question: are numbers valid? That is, are the numbers that show up on the graphs and tables in the reports are the same as the number reported on model output (*.out) files ?

**Comment by andkov** [comment]
@casslbrown, all models look ok.

Only one looks a bit fishy,  ```b1_male_a_pulmonary_memory_logicalmemoryimmed.out``` it has all the good parameters but a bad name. Could you please look into that?

**Comment by casslbrown** [comment]
Thanks! It was just a naming error I have corrected it.

________________________________

**Comment by casslbrown** [comment]
I am not sure the results extracted are what is intended. For example looking at the female, fev, digitordering for radc the p-value in the second column of the bivariate ISR table labeled slope is actually the p-value for the residual variance of physical measure slope (Residual Variances SP in MPlus output), the p-value in the residual variance column of the bivariate ISR table is the p-value for the correlation between each wave of physical measure and cognitive measure (ex P1 with C1 in Mplus output).


________________________________

**Comment by andkov** [comment]
@casslbrown, please do a face validity check of your BISRs now. extraction and extension scripts have been updated, which supposedly resolved your issue.  Please verify

**Comment by casslbrown** [comment]
Thanks! The intercept and slope correlation p-values are now matching mplus output. In the residual column it is still the value for individual occasions pulmonary and cognitive measures (ex., P1 with C1, P2 with C3), is that what it is supposed to be?

________________________________

**Comment by andkov** [comment]
It should match values for pc_SIGMA from from the output. Please check that they do or show what they match.

**Comment by casslbrown** [comment]
?Thanks! They do match. ? For RADC  all p-values in the bivariate ISR table match the mplus output.


________________________________

**Comment by andkov** [comment]
Thanks!
