### ISSUE TITLE
Bad p-value tiles in HRS

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#66]
There are a lot of significant p-values that don't have a  pink/magenta tile.   @andkov, let's look into this to see if it this is a parsing problem, or a graphical problem (or something else).

![image](https://cloud.githubusercontent.com/assets/1372890/8766302/e4373e84-2e2a-11e5-98db-125bad9ba915.png)

**Comment by andkov** [comment]
@wibeasley,  my brief exploration suggests the issue in models themselves, not parsing. Thanks for the specific  example

**Comment by chenkaiwu** [comment]
@andkov, are you suggesting that the p-values extracted from the outputs were not correct (i.e., match the CIs)? Thank you.

**Comment by andkov** [comment]
@chenkaiwu, it's still unclear. I thought it was the models, but my latest investigations may suggest CIs might disagree in significance with the raw output. I don't have a clear explanation of this to offer so far, but it will certainly be addressed. For now, trust the raw variance and pvalues.

**Comment by wibeasley** [comment]
...and if I understood Edwin correctly today, there are legitimate times when the significance of the correlation (which affect the CIs we display) don't correspond with the significance of the covariance (which affect the *p*-values extracted from M*plus*).

**Comment by andkov** [comment]
That was my understanding  too, but I can't document it yet.

**Comment by andkov** [comment]
Deprecated. 

#75 address this issue in a more general way, #14 was the first attempt to address it locally.
