### ISSUE TITLE
Forest plots for presentation

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#67]
@andkov, the old report is all connected again: https://github.com/IALSA/IALSA-2015-Portland/blob/master/synthesis/meta_report.md.  I'm going to add some more forest plots in the format you and Scott requested.

Here's an example now
![image](https://cloud.githubusercontent.com/assets/1372890/8814367/8a112002-3003-11e5-8cb1-dba19be9e2d8.png)

**Comment by ialsa-lab** [comment]
This is wonderful! Thanks @wibeasley

Sent from my iPhone, please excuse typing and T9 errors.

On Jul 21, 2015, at 11:52 PM, Will Beasley <notifications@github.com<mailto:notifications@github.com>> wrote:


@andkov<https://github.com/andkov>, the old report is all connected again: https://github.com/IALSA/IALSA-2015-Portland/blob/master/synthesis/meta_report.md. I'm going to add some more forest plots in the format you and Scott requested.

Here's an example now
[image]<https://cloud.githubusercontent.com/assets/1372890/8814367/8a112002-3003-11e5-8cb1-dba19be9e2d8.png>

-

**Comment by andkov** [comment]
Thanks, @wibeasley.  The closer the Forrest graph to the BISR, the better. But please give up if issues arise: we already got a demo piece in the old report

**Comment by wibeasley** [comment]
How's this direction, @andkov?  Do you really want the intercepts and residuals too?  It seemed like most of yesterday's interest was in the slopes.

Also, how do you feel about all showing all the covariate sets at once?  It consumes the vertical facet, and doesn't let us use it for different measures.  If I had to pick just one covariate set, what's the one people like most?  I'm going to try a third type of forest plot now
![image](https://cloud.githubusercontent.com/assets/1372890/8815001/53f9890c-300b-11e5-9005-e2bda0a170a2.png)

**Comment by andkov** [comment]
@wibeasley , slopes will be sufficient for tomorrow. in fact, there will be no time to focus on anything else. As for the model_type - great idea, please use "aeh".

**Comment by wibeasley** [comment]
@andkov, the graph should be ready now with the changes we just discussed.  The png is at https://github.com/IALSA/IALSA-2015-Portland/blob/master/synthesis/figure_meta/forest_static_bisr_covariates_aeh-1.png
  I tried two different pink/blue colors.  I prefer the first, but you can change to the brighter version if you comment/uncomment the lines below.

```r
palette_gender_dark <- c("#af6ca8", "#5a8fc1") #duller than below. http://colrd.com/image-dna/42282/ & http://colrd.com/image-dna/42275/
```
![image](https://cloud.githubusercontent.com/assets/1372890/8815831/8bd7f8a8-3016-11e5-91f6-750c3d790243.png)

```r
palette_gender_dark <- c("#f25091", "#6718f4") #brighter than above. http://colrd.com/palette/42278/
```
![image](https://cloud.githubusercontent.com/assets/1372890/8815792/efe4c0ac-3015-11e5-957c-fa1e219f7678.png)
