### ISSUE TITLE
Presentation for the WT

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#68]

**Comment by andkov** [comment]
@wibeasley, please help with presentation rendering. I can't make it launch from the readme

**Comment by wibeasley** [comment]
I'm sorry @andkov, I don't understand.  What's "WT" stand for again?

**Comment by ialsa-lab** [comment]
Sorry, @wibeasley, Wellcome Trust

Sent from my iPhone, please excuse typing and T9 errors.

On Jul 22, 2015, at 8:45 AM, Will Beasley <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry @andkov<https://github.com/andkov>, I don't understand. What's "WT" stand for again?

-

**Comment by wibeasley** [comment]
@andkov See the "raw git"answer here: http://stackoverflow.com/questions/6551446/can-i-run-html-files-directly-from-github-instead-of-just-viewing-their-source


Also I think it had to link to an html file (which isn't there), instead of a markdown or Rpres file.

**Comment by wibeasley** [comment]
This is done, correct @andkov?

**Comment by andkov** [comment]
Yes
