### ISSUE TITLE
checking for unhealthy .csv

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#8]
@wibeasley 
In the current state, some of the individual "collect_STUDY.r" scripts produce the .csv not populated improperly. When executed "model_synthesis.R" produces an error, stumbling on a unhealty .csv. (lines 55-58)

Note that in the individual "model_STUDY.r" , the "validate_output_filename" function is commented out (line 58), because throws an error and terminates

Goal state: unhealy, or absent .cvs from individual studies do not break the "collect_studies.R" script and do not interfere with report (synthesis/study_report.R) production

**Comment by wibeasley** [comment]
I'm putting this on the back burner.  It sounds like your existing approach is adequate for now.  We'll automate this later.
