### ISSUE TITLE
Unusual time points in ELSA

### ISSUE THREAD

**Issue by andkov** [IALSA/IALSA-2015-Portland#89]
@ampiccinin , @annierobi , @GracielaMuniz , Could anyone please comment on this? the time point for physical are different for the time point in cognitive. ELSA's [b1_female_aehplus_gait_grip](https://github.com/IALSA/IALSA-2015-Portland/blob/master/studies/elsa/physical/b1_female_aehplus_gait_grip.out), lines  93-94. Does this present require any special treatment during interpretation? 

```
>93  MODEL:  ip sp | p2 p4 p6 AT time2 time4 time6;
>94          ic sc | c1 c3 c5  AT time1 time3 time5;
```

**Comment by annierobi** [comment]
I uploaded the revised output. I must have forgotten to upload the new output with the revised data. At first we did not have all data points for gait.

**Comment by andkov** [comment]
Great, thank you!
