### ISSUE TITLE
ggplot errors 

### ISSUE THREAD

**Issue by andreazammit** [IALSA/IALSA-2015-Portland#93]
Hi @andkov 

I use this script for ggplots and I get the following errors. Can you help pleasE? 
```
spssdata = read.spss ("C:/Users/Andrea Zammit/Desktop/physical_noMCI7waves.sav",)
spssdata <- within(spssdata,{SubjectID<-factor(SubjectID)
female <- factor(Sex, levels=1:2, labels=c("male","female"))})
require (ggplot2)
PEK <- ggplot(data=spssdata$spssdata, aes(x = AgeYears, y = PeakFlowMax, group = SubjectID))
PEK + geom_line()+facet_grid(.~female)

Error in layout_base(data, cols, drop = drop) : 
At least one layer must contain all variables used for facetting
```

I have tried it using
na.omit in case it was a case of missing values.
i also used addtach(spssdata) in case it was because of file attachment issues... 

Thanks  a lot!!

**Comment by andkov** [comment]
I have two theories that could be tested by viewing the class of the variables ```female``` and ```SubjectID``` after line 3 in your script. Please run the following code after line three
```
spssdata[1:6,1:20] # to see some rows and columns
levels(spssdata$female) # to see how levels are assigned
table(spssdata$female) # to inspect summary of values
class(spssdata$SubjectID) # it should not be a factor, but an integer. I think that might be a part of the problem
```
I also do not understand the structure of you data when you use ```data=spssdata$spssdata``` it spells out "take a column ```spssdata``` in the dataframe ```spssdata```". Is that your intended thing to do?

**Comment by andreazammit** [comment]
@andkov , I write data=spssdata$spssdata because when I don't, i.e. when I write data=spssdata, I get the following error:
PEK <- ggplot(data=spssdata, aes(x = AgeYears, y = PeakFlowMax, group = SubjectID))
Error: ggplot2 doesn't know how to deal with data of class list
 
I did the commands you sent me and I got the following output:
spssdata[1:6,1:20]
Error in spssdata[1:6, 1:20] : incorrect number of dimensions
levels(spssdata$female)
NULL
 table(spssdata$female) 
< table of extent 0 >
class(spssdata$SubjectID)
[1] "numeric"

I don't understand why I get NULL levels when I have specified two levels (one for males and one for  females).. and what does incorrect number of dimensions mean? =/
I'm assuming SubjectID is okay being numeric since we don't want it to be a factor?

Thanks for the # explanations - they help!

**Comment by wibeasley** [comment]
@andreazammit, I'm guessing your `data.frame` is unconventionally defined, and it doesn't fit the expectations.  What's the output you get from this?
```r
class(spssdata)
sapply(spssdata, class)
summary(spssdata)
```

**Comment by andkov** [comment]
@andreazammit , you have a space between the function and the parentheses.
```
spssdata = read.spss ("C:/Users/Andrea Zammit/Desktop/physical_noMCI7waves.sav",)
```
This doesn't import the file. Instead use
```
spssdata = read.spss ("C:/Users/Andrea Zammit/Desktop/physical_noMCI7waves.sav",)
```
or use build in data iimport
![capture](https://cloud.githubusercontent.com/assets/2608073/10628587/d9a7d42a-777b-11e5-8e2f-d76072cfcbd8.PNG)

It is also a good idea to print a few rows of data before  you start graphing. Print the data for the variables you want to use in the graph so you can better understand how to map it and how to debug it. 
For example, after importing the data set request something like

```
head(spssdata[ ,c("SubjectID","Sex","AgeYears","PeakFlowMax")
```
Once you print the data and perhaps view it in a table
```
fix(spssdata)
View(spssdata)
```
you'll have a better idea about how to map it to a ggplot graph which uses these variables.

**Comment by andreazammit** [comment]
@wibeasley @andkov @ampiccinin 

Got it! Thanks :)  
 
I reimported my dataset using the package: memisc
easdata <- as.data.set(spss.system.file('C:/Users/Andrea Zammit/Desktop/physical_noMCI7waves.sav'))

I needed to install dev tools because it was giving me new errors because I am using an older version? (3.1.3).. I do have the new version, but the script worked on the older one.

devtools::install_github("hadley/plyr")
install.packages("devtools")

What formats are we saving as? 
I have them in tiff and JPEG

Thanks!

**Comment by wibeasley** [comment]
@andreazammit  A raster format like png works best for internal reports.  It's pretty portable, and doesn't have the compression artifacts like jpg & gif.

A vector format like png or svg is typically best for publication.  The copy editor can resize it and nothing gets pixelated or distorted.

**Comment by andreazammit** [comment]
@wibeasley  png it is. Done. Thanks so much!

**Comment by andkov** [comment]
@andreazammit , just FYI, GitHub Issues recently added drag-and-drop support for inserting images into comments like these (see 4th comment above). So you can share yous graph right here if you need to get other's opinion or help. Anyway, glad this worked out for you! :)

**Comment by andreazammit** [comment]
@andkov yes I noticed that this morning and I was thinking of attaching my graphs here - I just actually uploaded them into my shared EAS folder on github! :)

**Comment by andkov** [comment]
@andreazammit, you can also insert any image into a comment or an issue by providing a link to the online location of the image in the following markdown syntax:
```
![ short name of image ]( url to the image )
```
So, for example, if you wanted to link a newly created graph to this comment you would type
```
![peak flow](https://raw.githubusercontent.com/IALSA/IALSA-2015-Portland/master/studies/eas/Physical7waves/peakflow.png)
```
which would be displayed as
![peak flow](https://raw.githubusercontent.com/IALSA/IALSA-2015-Portland/master/studies/eas/Physical7waves/peakflow.png)

The key advantage of linking images to some stable location instead of drag-and-dropping them, is that when you change the image (regenerate the graph after having improved it) the images in this post will change too.

P.S. Congratulations on you first successful collaborative debugging in R!

**Comment by wibeasley** [comment]
@andkov, I like the permanency reason you gave.  Plus it's much more convenient that linking to a specific commit.  I know you keep some mini-tutorials for IALSA; maybe that point should be included.  And typing "ctrl+V" in the issues window is so quick.  

Also, I like using Window's "Snipping Tool" and Ubuntu's "Screenshot" when I need to grab some of the surrounding context.

![image](https://cloud.githubusercontent.com/assets/1372890/10640023/8bc2279e-77d8-11e5-8f22-b8bb11faddad.png)

**Comment by andreazammit** [comment]
@andkov 

Ha! That sounds like a big phrase, but I really just read a bunch of forums! 
 
That's pretty cool about the images! Just going to try a link.. 

![gripstrength](https://github.com/IALSA/IALSA-2015-Portland/blob/master/studies/eas/Physical7waves/gripstrength.png)

**Comment by andreazammit** [comment]
hmm. I'm trying dragging and dropping (sorry for the multiple emails now - just testing).  

![gripstrength](https://cloud.githubusercontent.com/assets/11074450/10640346/3c87ec86-77e2-11e5-9411-a34f23031dd9.png)

**Comment by wibeasley** [comment]
That first attempt was so close.

Instead of 
```
![gripstrength](https://github.com/IALSA/IALSA-2015-Portland/blob/master/studies/eas/Physical7waves/gripstrength.png)
```
do 
```
![raw](https://raw.githubusercontent.com/IALSA/IALSA-2015-Portland/master/studies/eas/Physical7waves/gripstrength.png)
```

It's sometimes confusing if you should link to the raw image in GitHub, or to the page with some HTML structure around it.

Basically go to the page you linked to, but then click the "Raw" button in the top right:
![image](https://cloud.githubusercontent.com/assets/1372890/10640465/656043ea-77da-11e5-86b1-2b9ceaa57daf.png)

**Comment by andreazammit** [comment]
@wibeasley 

Ahhhhh!! Got it!! :) 

![raw] (https://raw.githubusercontent.com/IALSA/IALSA-2015-Portland/master/studies/eas/Physical7waves/gripstrength.png)

**Comment by andkov** [comment]
@wibeasley , you made me think with "*linking to a specific commit*" phrase. If the the purpose of the issue thread is to receive **instruction** on the development of the graph, one would actually prefer to make the image permanent, otherwise changes suggested by unfolding comments  become less clear and the pedagogical re-play value of the thread diminishes.  On the other hand, if the purpose of the issue thread is to **develop** a graph then placing a permalink (in the issue's description, for example) will display the latest version of the graph, hiding production details for simplicity.

Good idea about the tutorials. I need to revamp that.

**Comment by ampiccinin** [comment]
Wow! Just today realized this was all here. Nice!!

**Comment by andreazammit** [comment]
:)

**Comment by wibeasley** [comment]
Glad it might work for you in the future, @ampiccinin. 

I think this issue is all wrapped up.  Someone reopen it if not.
