### ISSUE TITLE
Create APA tables

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IALSA-2015-Portland#97]
The live versions of the HTML are [here](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/physical/apa_tables/apa_tables.html).  Here are the current screenshots of the fixed effects table in HTML and in MS Word.  

For each unique [study] x [physical] x [cognitive] combination, there is a table for
* fixed effects
* random effects, and
* model details (eg, BIC, parameter count, convergence).

@GracielaMuniz, @ampiccinin, & @andkov, it sounds like you have the strongest opinions about the tables' purpose and designs.  What would you like to see added or modified?  I'm sure you'd like more added to the random effects table; I had trouble reading in between the lines of the "R eff" line (in Issue #86).  I'm happy to add more if I get some specific direction.  Ideally that table is sketched out like the fixed effects were in that photo.  @andkov was able to translate that to me.

![image](https://cloud.githubusercontent.com/assets/1372890/10778508/f69cf460-7cf4-11e5-8651-cb7620d84cc7.png)

![image](https://cloud.githubusercontent.com/assets/1372890/10778522/194c9fec-7cf5-11e5-983b-eae62d782f8f.png)

(*This issue deals with the programming of the tables.  Issue #35 is more about the distribution of the tables.*)

**Comment by wibeasley** [comment]
Hi @ampiccinin & @GracielaMuniz, did have any thoughts about the (a) existing fixed effects tables or the (b) random effects tables (described above)?

If there's nothing else you'd like changed with these APA tables, I'll close the issue in a few days.

**Comment by ampiccinin** [comment]
Sorry @wibeasley - I've been a bit caught up in other details. I also need a bit more time to try to articulate my thoughts about these tables. this is close, but do still need some changes. Can I get back to you after November 18?

**Comment by wibeasley** [comment]
No problem.

**Comment by andkov** [comment]
@ampiccinin, in your latest communication (2016-05-03), you have mentioned that we need a "growth curve model for each study to go into appendix". Please verify that we are on the same page about what should go into these tables.  Please review issue #97 from October, to get the historical context and the display design.  Right now we are thinking that including the fixed effects for each of the predictors might overwhelm the readers even in the appendix. Instead, a "growth model" is represented by the fixed effects of the intercept and slope of each process ( estimate, standard error and p-value for each gamma) 

Here is the sketch that we would like to actualize in the next few days. Please confirm that this is the correct direction.  Each study would report as many of the tables sketched below as there are unique outcome pairs submitted to the collective. 

If you think that a single table should be reported for one study, let's discuss it together. 

![image](https://cloud.githubusercontent.com/assets/2608073/15451260/8cd31722-1f6e-11e6-8100-a9afd6d83bbe.png)

**Comment by ampiccinin** [comment]
thanks @andkov - can you articulate your reasons for displaying the same four parameters from multiple models (a, ae, aeh, etc.)?

I had envisioned presenting (generally) a single model - the most appropriately complex one (may not be the most complex) - along, perhaps, with some indication of how much the parameters you listed change with the addition of the covariates. 

Another important point is that if the samples don't change much across the models within a study (they should not), then the differences in the estimates for grip in the bivariate grip-gait and grip-fev models should be negligible. We might want to compare them just to check, but we do not need to report all of them. We can just report one version each for grip, gait, and fev. this should reduce the size of the tables from Oct 27 by 50%.

We would likely want to be able to view the tables for the models of different complexity to make them easier to look at, but they would not all go in a manuscript.

I hope this helps.

**Comment by andkov** [comment]
Thanks, @ampiccinin, it does. Let me address the specifics. 

#### Model type

Your comment

> I had envisioned presenting (generally) a single model [...] **along, perhaps, with some indication of how much the parameters you listed change with the addition of the covariates.**

does in fact
> articulate[s my] reasons for displaying the same four parameters from multiple models (a, ae, aeh, etc.)?

that is, by displaying estimates in this fashion we examine how the parameters change as we add covariates. Did you have something else in mind how this could be expressed? I'm struggling to think of a different solution. 

Perhaps you are thinking about two informational displays: one (A) that allows examining how parameters change across model type (e.g. `a`, `ae`, `aeh`, etc., what was sketched above) and another one (B) that takes a single model type (`aehplus`, because it will  have the same constellation of predictors in all studies, unlike `full`) and allows examining how parameters change across outcome pairs ( rows would read: grip-gait, grip-fev, grip-pef). 

(B) is a subset of (A), so production would not be taxed too much to produce both, so we'll start with (A) to have for internal consumption, so we can better understand what's happening with the models, but only (B) should be styled in a way to be included into a manuscript. I like this plan, it will produce both the thorough model report that we need for scrutinizing model types, AND reader-friendly presentation that affords the big-picture evaluation. If this agreeable to you, we'll proceed with this plan. 

Please let me know if I am understanding you correctly. 

#### Subgroups 

Slightly switching topics: what do you think should be the strategy for reporting the subgroups? (male, female). One option is to have one outcome pair (e.g. grip-fev) to have two rows for females and males, one on top of another (as shown in the sketch). Another is to have two separate tables, one for each gender.  It seems that this decision needs to reflect the comparison you have in mind for the analysis, either one is fine from perspective of table implementation. Do you have a preference? 

There is another option: positioning model types side by side. This would add four more columns to the table.However, given the fact that each estimate contains in fact three values (estimate, se, and p-value) the decision to position subgroups side by side runs into display limitations : there won't be enough room on the page or it would look too crowded to make efficient use of the displayed information. In my opinion, this option is not viable. 

#### Sample size

As you said, due to the fact that missing values on the outcomes are deleted case-wise and affect the sample size used for the estimation of each model pair, perhaps it would be useful to reflect this information in the table, as you did in ISR table in phys-phys manuscript. I will add sample size counts to the table as an additional column.

**Comment by wibeasley** [comment]
If it helps to visualize, @ampiccinin, this is the [live version](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/table-growth-study/table-growth-study.html) of what @andkov and I did tonight.  Here's a [frozen version](https://github.com/IALSA/IALSA-2015-Portland/blob/dcb203464b018dd955f30a7043aadd76f77ea978/reports/table-growth-study/table-growth-study.md) that won't change when we update the code (but it also can't serve the dynamic JavaScript table).

There's a lot of cosmetics to fancy before it's APA-compliant (eg, monospace font and no vertical lines), but we'd like to settle the content and overall arrangement first.

![image](https://cloud.githubusercontent.com/assets/1372890/15452982/5e685f42-1fc7-11e6-9cfe-bb6f4763f556.png)

**Comment by ampiccinin** [comment]
@andkov - I meant that comments could be included in the text to describe any notable parameter changes - or common patterns of changes - across models. I really just want Table B, though something like your initial pivot table that would allow us to assemble all the corresponding estimates (of one or more parameters) across studies would also be useful. I never did walk you through all the tables I made by hand while preparing the Portland-physical-physical (PPP) paper, did I? 
Thanks!

**Comment by andkov** [comment]
@ampiccinin, thanks. 

> comments could be included in the text to describe any notable parameter changes 

yes, this makes sense. I think we are on the same page here.  Yes, only table B will be produced for the manuscript. However, the comments on the sensitivity of parameters across model types (or other variants) will be derived from some dynamic look-up tool that would allow customizable views. 

> I never did walk you through all the tables I made by hand while preparing the Portland-physical-physical (PPP) paper, did I? 

No, and it would be great to hear you talk through them with us - understanding how you think about crafting the arguments in the manuscript will be instrumental for the design of these tables, especially in this stage of the process, when things are mealable.

**Comment by wibeasley** [comment]
@ampiccinin, we've gotten better control of the density & formatting of the [`effects-fixed` report](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/effects-fixed/effects-fixed.html).  Later we'll create a simpler `effects-random` report.  It will be similar, but replace the gamma columns with BISR columns.  

Do you have any input on this fixed-effects report before we start on the random effects?  We hope to reuse most of the code, css, and structure.

![image](https://cloud.githubusercontent.com/assets/1372890/15456152/731cbe72-202d-11e6-8ff7-7de446ec06d7.png)

**Comment by ampiccinin** [comment]
thanks for the reminder, @andkov - I recall now that I had not replied to @wibeasley and because I had not known what to say. I feel like I keep asking for "A", and you keep giving me "B". I then sent a bunch of "C" to give you an idea of what else would be helpful (how I had actually organized the information myself while working with the output), and might help to bridge the gap between my "A" and your "B", but you again sent me "B". Maybe you could explain to me why you think "B" is helpful so I can gain some insight into my apparent confusion. thanks!  
@smhofer, @GracielaMuniz  - I imagine this would be helpful to you as well?

**Comment by andkov** [comment]
@ampiccinin , i am a bit confused too. In the comment 10 days ago you said:
> I really just want Table B, though something like your initial pivot table that would allow us to assemble all the corresponding estimates (of one or more parameters) across studies would also be useful. 

which I defined in the comment 11 days ago as

> (B) that takes a single model type (e.g. aehplus, ) and allows examining how parameters change across outcome pairs ( rows would read: grip-gait, grip-fev, grip-pef).

This table (B) is the one we've produced for [Random Effects](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/effects-random/effects-random.html) ( correlations between intercepts, slopes, and residuals) and [Fixed Effects](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/effects-fixed/effects-fixed.html) (what you described in your email to me on 5016-05-18 as *growth model table for each study separately to go in appendix*) they are the static tables in each report. At the same time, all the information to form table (A) is contained in the dynamic tables, which could be adjusting to the immediate focus of inquiry (appendix). 

Are we talking about the same table B?

**Comment by ampiccinin** [comment]
Table B: I'm thinking something like this, with a column for each outcome. In a situation like the one below, each study has one outcome so everything can go in one table. With one outcome per study, separated by sex, we might have one table for men and another for women. The key is to facilitate the most relevant comparisons. with multiple outcomes and stratifications per study, we might assemble results for each study in separate tables, or results for each outcome, depending on the situation. For Portland physical-physical, if would make sense to table similar outcomes together (e.g., all gait estimates in a single table of all studies)

For the bivariate change model, a second table including the I-I, S-S, and R-R correlations, as in the October IJE submission, would also be required.

(if image does not appear correctly, I will try again. If I had this table to do over, I would consider altering the rows to show Intercept, then covariates of intercept, Time/Slope, then covariates of time)

![image](https://cloud.githubusercontent.com/assets/8059389/15806474/faf81e38-2af8-11e6-9401-0f1c3c873255.png)

**Comment by wibeasley** [comment]
Thanks for the feedback @ampiccinin.  I think there are still some details with that plan that could use more discussion.  It's difficult for me to reconcile our different perspectives over email with several day between responses.  I'm pretty busy Monday, but I'm fairly free the rest of the week if you're available to talk and share screens.  @andkov, if you find a time that the two of you are free after Monday, I bet I can make it too.  I bet we could sketch out the tables within 20 minutes over the phone sharing screens.

## Versions

It sounds like there are at least two versions of "Table B"s that are needed.  (And when people say "table" in this context, I think "set of tables" is more accurate.) 

This existing version meets the requested need that "participants can copy & paste our automatically produced tables into their study-specific manuscripts".  (I'm paraphrasing from memory, so please correct me if I'm misremembering.)  This version groups together the *outcomes* associated with a specific **study**.  I'll call this "B-1" for now.

If I'm interpreting correctly, you'd liked a similar series of tables (but with a different order of rows/groupings) that is better for workshop-wide comparisons.  This version groups together *studies* associated with a specific **outcome**.  I'll call this "B-2" for now.

#### Table Set B-1
Purpose: allow workshop participants to copy & paste into their individual manuscripts.

| attribute | values |
| --------  | ------ |
| columns | Process pair, <em>n, r<sub>ii</sub>, r<sub>ss</sub>, r<sub>rr</sub></em> |
| rows | physical-cognitive pairs |
| tables | unique studies |

*note: each 'dense' <em>r</em> column contains the r, se, & p.*

#### Table Set B-2
Purpose: meta-analysis-ish tables that facilitate workshop-wide comparisons of a single physical-cognitive pair.

| attribute | values |
| --------  | ------ |
| columns | Study, <em>n, r<sub>ii</sub>, r<sub>ss</sub>, r<sub>rr</sub></em> |
| rows | studies |
| tables | genders |
| groups of tables | unique physical-cognitive pairs |

*note: each 'dense' <em>r</em> column contains the r, se, & p.*

@ampiccinin, if the [effects-random](https://rawgit.com/IALSA/IALSA-2015-Portland/master/reports/effects-random/effects-random.html) report contained both versions of these table sets, would it address all the all needs expressed by you and @GracielaMuniz?  If there's a third version (and you're not free to meet & share screens), can you spell it out like we have with Table Sets B-1 & B-2 above?

## Other comments

> I'm thinking something like this, with a column for each outcome. 

@ampiccinin, let's discuss this some more, because I might be misunderstanding.  I think these tables would be far too wide for printed manuscripts; it would even be wide for floating html tables.  Plus, each these columns/cells don't really show a *single* outcome; they show *pairs* of outcomes, which would make the tables even wider.  There are 70+ different populated combinations of outcomes.

>For Portland physical-physical, if would make sense
 to table similar outcomes together (e.g., all gait estimates in a single table of all studies)

That's basically what the existing B-1 tables do now for physical-cognitive.  Within a table, all the `gait`s are together, followed by all the `grip`s, followed by all the `pef`s.  I think a simple horizontal rule/lines between the groups could be better than creating three different tables.  (We didn't add the rules in the html version because copying floating lines over to MSWord can create formatting headaches, and it's simple enough for the participant to add the lines where they want.)

For "physical-physical", do you mean have redundant cells?  The "gait" table has gait-grip and the "grip" table has grip-gait?  I'm not opposed to that, but I want to double-check.

**Comment by ampiccinin** [comment]
Sets of tables - yes.

**Comment by ampiccinin** [comment]
"these tables would be far too wide for printed manuscripts" - could be divided into multiple tables.

"these columns/cells don't really show a single outcome; they show pairs of outcomes,"  
- I think this is where our perspectives are diverging. the bivariate growth model is made up of two growth models, joined by the correlations allowed between the intercepts, slopes and residuals. Whether outcome y1 is paired with y2 or y3, its growth model estimates should be negligibly different. If they are not, this indicates a problem. so we do not need to present the growth model for each pair, only for each outcome. Obviously we should do a quick comparison of some sort, to ensure that the estimates do not markedly change, but they do not all need to go in a manuscript/appendix. 

I am sometimes confused by your reference to columns versus rows

**Comment by wibeasley** [comment]
@ampiccinin, good, I feel we're getting closer to identifying where some of the divergences.  For example, during my visit last week I thought the task was to replicate Tables 3 & 4 of the [previous manuscript](https://github.com/IALSA/IALSA-2015-Portland/blob/master/projects/physical-physical/manuscript/Submitted%20manuscript.pdf) (see below).

Considering we weren't even talking about the same values being tabled (eg, you were talking about slopes, while I was talking about correlations between slopes), let's knock this out over the phone sharing screens to reduce the back-and-forth.  When are you available this week, @ampiccinin?  I'm relatively free after tomorrow (Wed-Friday).  @andkov, when are you free?

![image](https://cloud.githubusercontent.com/assets/1372890/15835697/bdd0bd7c-2bf6-11e6-8a41-541067c1fedf.png)

**Comment by ampiccinin** [comment]
Wednesday is rather unpredictable for me at this point. I think I should have some time on Thursday. In either case, I need to nail down some other commitments to see how best to fit this into my schedule. do either of you have any constraints?

**Comment by andkov** [comment]
I'm presenting at CPA on Friday at 13:45. Wednesday I'll be at island Health until 2 pm. Thursday is good, Tuesday is good.

**Comment by ampiccinin** [comment]
Ok - let's plan on Thursday. I'll post again once I've clarified the timing of some other obligations.

**Comment by ampiccinin** [comment]
Thanks for the reminder. Around 9am should work.

**Comment by andkov** [comment]
@wibeasley does this work for you?

**Comment by wibeasley** [comment]
@ampiccinin & @andkov, here's a shot of the tables were were sketching out during the meeting.

A few notes:

1. @ampiccinin will play around with the "Random Effects for CAR" version to see what best suits the workshop-wide/CAR manuscript.
1. There are currently three versions of the same information
    * the "Random Effects for study-specific manuscripts" version  groups all the models of a study together, which will allow them to copy (a subset of) our tables into their manuscripts.  To allow their readers to dive into their results, the cells will have the estimate, se, & p-value
    * the "Random Effects for CAR" version groups together all the process-pairs.  To reduce clutter, the cells have only the estimates & significance-asterisks.
    * the dynamic & exhaustive version that will allow interested parties to make any comparison they want.  At least for a few years, the Javascript table will be hosted on an IALSA website and on GitHub.  At least for a few decades (theoretically), the whole repo will archived by the third-party Zenodo.  (Here's an [example](https://zenodo.org/record/44900#.V1moY_krLmE) of what we did for a recent textbook.)
1. The gray columns won't be included in the final tables.  Because they're constant values, it can be factored out into the table title.
1. Once the tables of *correlations* are more stable, we'll design the tables of *growth curve components*.
1. The xlsx file we sketched can be [downloaded](https://github.com/IALSA/IALSA-2015-Portland/blob/master/sandbox/table-planning/possible-tables.xlsx) after clicking the 'View Raw' button.

![image](https://cloud.githubusercontent.com/assets/1372890/15939352/fd924172-2e3c-11e6-986d-069830a67899.png)

**Comment by ampiccinin** [comment]
2 sex x 3 phys x 6 cog x 10 studies = 360 tables (remind me how we get 1300?)
2 scenarios attached. I prefer #1, but of course it would depend on the # of phys and cog. Please tell me if I'm missing something!

[Table scenarios.xlsx](https://github.com/IALSA/IALSA-2015-Portland/files/314221/Table.scenarios.xlsx)

**Comment by andkov** [comment]
Here is the [dynamic table of all models ](https://rawgit.com/IALSA/IALSA-2015-Portland/master/sandbox/inspect-extracted-results/inspect-extracted-raw.html)we have so far (before we conduct renaming and classification, to examine what actually  has been submitted) 

The table is the closest so far we have to the growth curve table (includes all model parameters that we;ve extracted, bar model information indices). There are 1271 unique entries (once you select one index) which correspond to models. You can see that there are many more cognitive measures than 6.

**Comment by andkov** [comment]
## models vs processes perspective
> I think this is where our perspectives are diverging. the bivariate growth model is made up of two growth models, joined by the correlations allowed between the intercepts, slopes and residuals. Whether outcome y1 is paired with y2 or y3, its growth model estimates should be negligibly different. If they are not, this indicates a problem. so we do not need to present the growth model for each pair, only for each outcome. Obviously we should do a quick comparison of some sort, to ensure that the estimates do not markedly change, but they do not all need to go in a manuscript/appendix.



## Physical and cognitive measure (census) 
```r
> sort(unique(ds_full$process_a))
[1] "fev"    "fev100" "gait"   "grip"   "nophys" "pef"    "tug"   
```

```r
> sort(unique(ds_full$process_b))
 [1] "analogies"   "block"       "bnt"         "bstory_de"  
 [5] "bstory_im"   "categories"  "digit_b"     "digit_f"    
 [9] "digit_o"     "digit_tot"   "fas"         "fig_id"     
[13] "fig_logic"   "fig_mem"     "fluency"     "ideas"      
[17] "information" "letter"      "line"        "logic_de"   
[21] "logic_im"    "logic_tot"   "matrices"    "mir"        
[25] "mmms"        "nart"        "num_comp"    "piccomp"    
[29] "prose_im"    "psif"        "raven"       "rotate"     
[33] "serial7"     "symbol"      "synonyms"    "tics"       
[37] "trailsb"     "waisgeneral" "waisvocab"   "word_de"    
[41] "word_im"     "word_rec"   
```

**Comment by andkov** [comment]
Agenda:

Table of correlations
1) Are we good to proceed with existing sketch for table of correlations? What changes are needed?

Table of growth curve components
2) models vs processes perspective (not the same!)
3) Is the [dynamic table of all models](https://rawgit.com/IALSA/IALSA-2015-Portland/master/sandbox/inspect-extracted-results/inspect-extracted-raw.html) an acceptable format for EXPLORATIVE and INTERNAL ACCOUNTING tables?

**Comment by andkov** [comment]
- goal I : describe MODELS as they come out from Mplus
- goal II : describe processes in various contexts (studies, model_types)

**Comment by wibeasley** [comment]
This issue is much better understood, and is being split into #129 and #130.
